import Phaser from 'phaser';
import { drawIsoTerrain } from '../world/isoTerrain';
import { isoDepth, isoToWorld, worldToIso } from '../world/iso';
import { BUILDING_SPECS, type BuildingKind } from '../economy/buildingTypes';
import { canAfford, canPlaceBuilding, canTrain, spendResources, UNIT_COSTS, UNIT_TRAIN_TIME_MS } from '../economy/productionRules';
import type { Building, ProductionOrder } from '../economy/productionTypes';
import { PortraitPanel } from '../ui/PortraitPanel';

type Formation = 'line' | 'column' | 'square' | 'wedge' | 'doubleLine' | 'skirmish';
type UnitKind = 'worker' | 'soldier' | 'specialist' | 'cavalry' | 'artillery';
type Resources = { food: number; wood: number; iron: number; gold: number; population: number; populationCap: number };
type UnitSpec = { label: string; short: string; color: number; width: number; height: number; speed: number; hp: number; morale: number; ammo: number; range: number; damage: number; moraleDamage: number; reloadMs: number };

const WORLD_WIDTH = 26;
const WORLD_HEIGHT = 20;
const UNIT_KINDS: UnitKind[] = ['worker', 'soldier', 'specialist', 'cavalry', 'artillery'];
const UNIT_SPECS: Record<UnitKind, UnitSpec> = {
  worker: { label: 'Рабочий', short: 'W', color: 0x22c55e, width: 12, height: 12, speed: 1.2, hp: 70, morale: 70, ammo: 0, range: 0, damage: 4, moraleDamage: 2, reloadMs: 1000 },
  soldier: { label: 'Воин', short: 'S', color: 0x2563eb, width: 14, height: 14, speed: 1.3, hp: 100, morale: 100, ammo: 12, range: 5.2, damage: 24, moraleDamage: 12, reloadMs: 1400 },
  specialist: { label: 'Специалист', short: 'P', color: 0xa855f7, width: 13, height: 13, speed: 1.45, hp: 85, morale: 120, ammo: 18, range: 6, damage: 18, moraleDamage: 20, reloadMs: 1100 },
  cavalry: { label: 'Кавалерия', short: 'C', color: 0xf59e0b, width: 20, height: 12, speed: 2.4, hp: 130, morale: 115, ammo: 6, range: 3, damage: 32, moraleDamage: 22, reloadMs: 1250 },
  artillery: { label: 'Артиллерия', short: 'A', color: 0x64748b, width: 24, height: 18, speed: 0.7, hp: 160, morale: 90, ammo: 8, range: 11, damage: 70, moraleDamage: 40, reloadMs: 3200 },
};

type Unit = { id: number; kind: UnitKind; battalionId: number | null; world: Phaser.Math.Vector2; sprite: Phaser.GameObjects.Rectangle; label: Phaser.GameObjects.Text; selected: boolean; target: Phaser.Math.Vector2 | null; speed: number; hp: number; morale: number; ammo: number; range: number; damage: number; moraleDamage: number; reloadMs: number; lastShotAt: number };
type Battalion = { id: number; name: string; unitIds: Set<number>; formation: Formation; angle: number };

export class BattleScene extends Phaser.Scene {
  private units: Unit[] = [];
  private enemies: Unit[] = [];
  private battalions: Battalion[] = [];
  private buildings: Building[] = [];
  private selectedIds = new Set<number>();
  private selectedBuildingId: number | null = null;
  private placementKind: BuildingKind | null = null;
  private selectionStart: Phaser.Math.Vector2 | null = null;
  private rightDragStart: Phaser.Math.Vector2 | null = null;
  private selectionRect!: Phaser.GameObjects.Rectangle;
  private commandPreview!: Phaser.GameObjects.Graphics;
  private commandLines!: Phaser.GameObjects.Graphics;
  private battalionGraphics!: Phaser.GameObjects.Graphics;
  private topBar!: Phaser.GameObjects.Text;
  private bottomPanel!: Phaser.GameObjects.Graphics;
  private portraitPanel!: PortraitPanel;
  private minimap!: Phaser.GameObjects.Graphics;
  private nextId = 1;
  private nextBuildingId = 1;
  private nextOrderId = 1;
  private nextBattalionId = 1;
  private formation: Formation = 'line';
  private resources: Resources = { food: 700, wood: 900, iron: 260, gold: 220, population: 0, populationCap: 20 };

  constructor() { super('BattleScene'); }

  create(): void {
    this.cameras.main.setBounds(0, 0, 3200, 1800);
    this.cameras.main.scrollX = 720;
    this.cameras.main.scrollY = 40;
    this.input.mouse?.disableContextMenu();
    drawIsoTerrain(this, WORLD_WIDTH, WORLD_HEIGHT);
    this.commandLines = this.add.graphics().setDepth(5000);
    this.battalionGraphics = this.add.graphics().setDepth(5001);
    this.commandPreview = this.add.graphics().setDepth(6000);
    this.selectionRect = this.add.rectangle(0, 0, 1, 1, 0x84cc16, 0.15).setStrokeStyle(2, 0xa3e635).setVisible(false).setDepth(9000);
    this.createHud();

    this.createBuilding(6, 8, 'town_center', true);
    this.spawnUnitBlock(6.2, 9.2, 4, 2, 'worker', false, false);
    this.resources.population = this.units.length;

    this.input.on('pointerdown', this.onPointerDown, this);
    this.input.on('pointermove', this.onPointerMove, this);
    this.input.on('pointerup', this.onPointerUp, this);
    this.input.keyboard?.on('keydown-ONE', () => this.setFormation('line'));
    this.input.keyboard?.on('keydown-TWO', () => this.setFormation('column'));
    this.input.keyboard?.on('keydown-THREE', () => this.setFormation('square'));
    this.input.keyboard?.on('keydown-FOUR', () => this.setFormation('wedge'));
    this.input.keyboard?.on('keydown-FIVE', () => this.setFormation('doubleLine'));
    this.input.keyboard?.on('keydown-SIX', () => this.setFormation('skirmish'));
    this.input.keyboard?.on('keydown-G', () => this.createBattalionFromSelection());
    this.input.keyboard?.on('keydown-U', () => this.ungroupSelectedBattalions());
    this.input.keyboard?.on('keydown-R', () => this.reformSelectedInPlace());
    this.input.keyboard?.on('keydown-ESC', () => { this.placementKind = null; this.clearSelection(); });
    this.input.keyboard?.on('keydown-H', () => this.beginPlacement('house'));
    this.input.keyboard?.on('keydown-B', () => this.beginPlacement('barracks'));
    this.input.keyboard?.on('keydown-S', () => this.beginPlacement('stable'));
    this.input.keyboard?.on('keydown-F', () => this.beginPlacement('foundry'));
    this.input.keyboard?.on('keydown-T', () => this.trainFromSelectedBuilding('worker'));
    this.input.keyboard?.on('keydown-Q', () => this.trainFromSelectedBuilding('soldier'));
    this.input.keyboard?.on('keydown-E', () => this.trainFromSelectedBuilding('specialist'));
    this.input.keyboard?.on('keydown-C', () => this.trainFromSelectedBuilding('cavalry'));
    this.input.keyboard?.on('keydown-A', () => this.trainFromSelectedBuilding('artillery'));
  }

  update(time: number, delta: number): void { this.updateCamera(delta); this.updateBuildings(delta); this.updateUnits(this.units, delta); this.updateUnits(this.enemies, delta); this.updateCombat(time); this.renderUnitState(); this.renderBuildingState(); this.renderBattalions(); this.updateHud(); }
  private createHud(): void { this.topBar = this.add.text(8, 4, '', { fontFamily: 'Georgia, serif', fontSize: '14px', color: '#f5e6b8', backgroundColor: '#2b1c11dd', padding: { x: 10, y: 4 } }).setScrollFactor(0).setDepth(3000); this.bottomPanel = this.add.graphics().setScrollFactor(0).setDepth(2800); this.portraitPanel = new PortraitPanel(this); this.minimap = this.add.graphics().setScrollFactor(0).setDepth(3100); }
  private beginPlacement(kind: BuildingKind): void { if (!canAfford(this.resources, BUILDING_SPECS[kind].cost)) return; this.placementKind = kind; }
  private placeBuilding(kind: BuildingKind, x: number, y: number): void { if (!canAfford(this.resources, BUILDING_SPECS[kind].cost) || !canPlaceBuilding(this.buildings, x, y, kind)) return; spendResources(this.resources, BUILDING_SPECS[kind].cost); this.createBuilding(x, y, kind, false); this.placementKind = null; }
  private createBuilding(x: number, y: number, kind: BuildingKind, completed: boolean): Building { const spec = BUILDING_SPECS[kind]; const p = worldToIso(x, y); const sprite = this.add.rectangle(p.x, p.y - 16, spec.width, spec.height, spec.color, completed ? 1 : 0.45).setStrokeStyle(2, 0x111827); const label = this.add.text(p.x, p.y - 42, spec.short, { fontFamily: 'Arial', fontSize: '11px', color: '#f8fafc' }).setOrigin(0.5); const building: Building = { id: this.nextBuildingId++, kind, world: new Phaser.Math.Vector2(x, y), sprite, label, completed, progressMs: completed ? spec.buildTimeMs : 0, buildTimeMs: spec.buildTimeMs, hitpoints: spec.hitpoints, selected: false, queue: [] }; this.buildings.push(building); if (completed && spec.populationCapBonus) this.resources.populationCap += spec.populationCapBonus; this.syncBuildingSprite(building); return building; }
  private selectBuilding(building: Building): void { this.clearSelection(); this.selectedBuildingId = building.id; this.buildings.forEach((b) => b.selected = b.id === building.id); }
  private trainFromSelectedBuilding(unitKind: UnitKind): void { const building = this.buildings.find((b) => b.id === this.selectedBuildingId); if (!building || !canTrain(building, unitKind) || !canAfford(this.resources, UNIT_COSTS[unitKind]) || this.resources.population >= this.resources.populationCap) return; spendResources(this.resources, UNIT_COSTS[unitKind]); building.queue.push({ id: this.nextOrderId++, unitKind, progressMs: 0, trainTimeMs: UNIT_TRAIN_TIME_MS[unitKind] }); }
  private updateBuildings(delta: number): void { for (const building of this.buildings) { const spec = BUILDING_SPECS[building.kind]; if (!building.completed) { building.progressMs += delta; if (building.progressMs >= building.buildTimeMs) { building.completed = true; building.progressMs = building.buildTimeMs; building.sprite.setAlpha(1); if (spec.populationCapBonus) this.resources.populationCap += spec.populationCapBonus; } } const current = building.queue[0]; if (building.completed && current) { current.progressMs += delta; if (current.progressMs >= current.trainTimeMs) { building.queue.shift(); this.createUnit(building.world.x + 0.8, building.world.y + 0.8, current.unitKind, false, null); this.resources.population = this.units.length; } } this.syncBuildingSprite(building); } }
  private syncBuildingSprite(building: Building): void { const p = worldToIso(building.world.x, building.world.y); const d = isoDepth(building.world.x, building.world.y); building.sprite.setPosition(p.x, p.y - 18).setDepth(d - 2); building.label.setPosition(p.x, p.y - 48).setDepth(d + 1); }

  private spawnUnitBlock(x: number, y: number, cols: number, rows: number, kind: UnitKind, enemy: boolean, autoBattalion: boolean): void { const battalionId = !enemy && autoBattalion ? this.nextBattalionId++ : null; const unitIds = new Set<number>(); const spec = UNIT_SPECS[kind]; for (let r = 0; r < rows; r++) for (let c = 0; c < cols; c++) { const unit = this.createUnit(x + c * 0.35, y + r * 0.35, kind, enemy, battalionId); if (!enemy) unitIds.add(unit.id); } if (!enemy && battalionId !== null) this.battalions.push({ id: battalionId, name: `${spec.label} ${battalionId}`, unitIds, formation: 'line', angle: 0 }); }
  private createUnit(x: number, y: number, kind: UnitKind, enemy: boolean, battalionId: number | null): Unit { const spec = UNIT_SPECS[kind]; const color = enemy ? 0x8b1e1e : spec.color; const p = worldToIso(x, y); const sprite = this.add.rectangle(p.x, p.y, spec.width, spec.height, color).setStrokeStyle(1, 0x111827); const label = this.add.text(p.x, p.y - 16, spec.short, { fontFamily: 'Arial', fontSize: '10px', color: '#e5e7eb' }).setOrigin(0.5).setDepth(20); const unit: Unit = { id: this.nextId++, kind, battalionId, world: new Phaser.Math.Vector2(x, y), sprite, label, selected: false, target: null, speed: enemy ? spec.speed * 0.85 : spec.speed, hp: spec.hp, morale: spec.morale, ammo: spec.ammo, range: spec.range, damage: spec.damage, moraleDamage: spec.moraleDamage, reloadMs: spec.reloadMs, lastShotAt: 0 }; (enemy ? this.enemies : this.units).push(unit); return unit; }
  private pointerWorld(pointer: Phaser.Input.Pointer): Phaser.Math.Vector2 { const p = pointer.positionToCamera(this.cameras.main) as Phaser.Math.Vector2; return isoToWorld(p.x, p.y); }
  private pointerIso(pointer: Phaser.Input.Pointer): Phaser.Math.Vector2 { return pointer.positionToCamera(this.cameras.main) as Phaser.Math.Vector2; }
  private onPointerDown(pointer: Phaser.Input.Pointer): void { const world = this.pointerWorld(pointer); const iso = this.pointerIso(pointer); if (pointer.rightButtonDown()) { this.rightDragStart = world.clone(); this.drawCommandPreview(this.rightDragStart, world); return; } if (this.placementKind) { this.placeBuilding(this.placementKind, Math.round(world.x * 2) / 2, Math.round(world.y * 2) / 2); return; } const building = this.findBuildingAtIso(iso.x, iso.y); if (building) { this.selectBuilding(building); return; } this.selectionStart = iso.clone(); this.selectionRect.setPosition(iso.x, iso.y).setSize(1, 1).setVisible(true); }
  private onPointerMove(pointer: Phaser.Input.Pointer): void { const world = this.pointerWorld(pointer); const iso = this.pointerIso(pointer); if (this.rightDragStart && pointer.rightButtonDown()) { this.drawCommandPreview(this.rightDragStart, world); return; } if (!this.selectionStart || !pointer.isDown) return; const x = Math.min(this.selectionStart.x, iso.x); const y = Math.min(this.selectionStart.y, iso.y); const w = Math.abs(iso.x - this.selectionStart.x); const h = Math.abs(iso.y - this.selectionStart.y); this.selectionRect.setPosition(x + w / 2, y + h / 2).setSize(w, h); }
  private onPointerUp(pointer: Phaser.Input.Pointer): void { const world = this.pointerWorld(pointer); const iso = this.pointerIso(pointer); if (this.rightDragStart && pointer.rightButtonReleased()) { const dragDistance = Phaser.Math.Distance.Between(this.rightDragStart.x, this.rightDragStart.y, world.x, world.y); const angle = dragDistance > 0.25 ? Phaser.Math.Angle.Between(this.rightDragStart.x, this.rightDragStart.y, world.x, world.y) : 0; this.issueMoveCommand(this.rightDragStart.x, this.rightDragStart.y, angle); this.rightDragStart = null; this.commandPreview.clear(); return; } if (!this.selectionStart || pointer.rightButtonReleased()) return; const bounds = new Phaser.Geom.Rectangle(Math.min(this.selectionStart.x, iso.x), Math.min(this.selectionStart.y, iso.y), Math.abs(iso.x - this.selectionStart.x), Math.abs(iso.y - this.selectionStart.y)); this.clearSelection(); this.units.forEach((unit) => { if (Phaser.Geom.Rectangle.Contains(bounds, unit.sprite.x, unit.sprite.y) || Phaser.Math.Distance.Between(unit.sprite.x, unit.sprite.y, this.selectionStart!.x, this.selectionStart!.y) < 18) { unit.selected = true; this.selectedIds.add(unit.id); } }); this.expandSelectionToBattalions(); this.selectionStart = null; this.selectionRect.setVisible(false); }
  private findBuildingAtIso(x: number, y: number): Building | null { return this.buildings.find((b) => Phaser.Math.Distance.Between(x, y, b.sprite.x, b.sprite.y) < 34) ?? null; }
  private setFormation(formation: Formation): void { this.formation = formation; this.getSelectedBattalions().forEach((b) => b.formation = formation); }
  private issueMoveCommand(x: number, y: number, angle: number): void { const selected = this.units.filter((u) => this.selectedIds.has(u.id)); const battalions = this.getSelectedBattalions(); const groupedIds = new Set<number>(); battalions.forEach((b) => b.unitIds.forEach((id) => groupedIds.add(id))); if (battalions.length > 0) { const groupOffsets = this.getGroupOffsets(battalions.length, angle); battalions.forEach((b, index) => { b.angle = angle; b.formation = this.formation; const members = this.units.filter((u) => b.unitIds.has(u.id)); const base = groupOffsets[index] ?? new Phaser.Math.Vector2(0, 0); const offsets = this.getFormationOffsets(members.length, angle, b.formation); members.forEach((unit, unitIndex) => { const offset = offsets[unitIndex] ?? new Phaser.Math.Vector2(0, 0); unit.target = new Phaser.Math.Vector2(x + base.x + offset.x, y + base.y + offset.y); }); }); } const loose = selected.filter((u) => !groupedIds.has(u.id)); const looseOffsets = this.getFormationOffsets(loose.length, angle, this.formation); loose.forEach((unit, index) => { const offset = looseOffsets[index] ?? new Phaser.Math.Vector2(0, 0); unit.target = new Phaser.Math.Vector2(x + offset.x, y + offset.y); }); this.commandLines.clear(); this.drawFormationGhost(this.commandLines, x, y, angle, selected.length, 0xfacc15, 0.65, this.formation); }
  private getGroupOffsets(count: number, angle: number): Phaser.Math.Vector2[] { const raw: Phaser.Math.Vector2[] = []; const spacing = 2.2; for (let i = 0; i < count; i++) raw.push(new Phaser.Math.Vector2((i - (count - 1) / 2) * spacing, 0)); return raw.map((v) => this.rotate(v, angle)); }
  private getFormationOffsets(count: number, angle: number, formation = this.formation): Phaser.Math.Vector2[] { const raw: Phaser.Math.Vector2[] = []; const gap = formation === 'skirmish' ? 0.55 : 0.35; if (formation === 'column') { for (let i = 0; i < count; i++) raw.push(new Phaser.Math.Vector2((i % 4) * gap - 1.5 * gap, Math.floor(i / 4) * gap)); } else if (formation === 'square') { const side = Math.ceil(Math.sqrt(count)); for (let i = 0; i < count; i++) raw.push(new Phaser.Math.Vector2((i % side) * gap - (side - 1) * gap / 2, Math.floor(i / side) * gap - (side - 1) * gap / 2)); } else if (formation === 'wedge') { let placed = 0; for (let row = 0; placed < count; row++) { const rowCount = row * 2 + 1; for (let col = 0; col < rowCount && placed < count; col++) { raw.push(new Phaser.Math.Vector2((col - row) * gap, row * gap)); placed++; } } } else if (formation === 'doubleLine') { const width = Math.ceil(count / 2); for (let i = 0; i < count; i++) raw.push(new Phaser.Math.Vector2((i % width) * gap - (width - 1) * gap / 2, Math.floor(i / width) * gap)); } else { const width = formation === 'skirmish' ? Math.min(16, Math.max(1, count)) : Math.min(12, Math.max(1, count)); for (let i = 0; i < count; i++) raw.push(new Phaser.Math.Vector2((i % width) * gap - (width - 1) * gap / 2, Math.floor(i / width) * gap)); } return raw.map((v) => this.rotate(v, angle)); }
  private rotate(v: Phaser.Math.Vector2, angle: number): Phaser.Math.Vector2 { return new Phaser.Math.Vector2(v.x * Math.cos(angle) - v.y * Math.sin(angle), v.x * Math.sin(angle) + v.y * Math.cos(angle)); }
  private drawCommandPreview(start: Phaser.Math.Vector2, end: Phaser.Math.Vector2): void { const count = this.selectedIds.size; const angle = Phaser.Math.Distance.Between(start.x, start.y, end.x, end.y) > 0.25 ? Phaser.Math.Angle.Between(start.x, start.y, end.x, end.y) : 0; this.commandPreview.clear(); const s = worldToIso(start.x, start.y); const e = worldToIso(end.x, end.y); this.commandPreview.lineStyle(2, 0xfacc15, 0.85).lineBetween(s.x, s.y, e.x, e.y).strokeCircle(s.x, s.y, 10); this.drawFormationGhost(this.commandPreview, start.x, start.y, angle, count, 0xfacc15, 0.35, this.formation); }
  private drawFormationGhost(g: Phaser.GameObjects.Graphics, x: number, y: number, angle: number, count: number, color: number, alpha: number, formation: Formation): void { const offsets = this.getFormationOffsets(count, angle, formation); g.lineStyle(1, color, alpha); offsets.forEach((offset) => { const p = worldToIso(x + offset.x, y + offset.y); g.strokeRect(p.x - 7, p.y - 7, 14, 14); }); }
  private createBattalionFromSelection(): void { const selected = this.units.filter((u) => this.selectedIds.has(u.id)); if (selected.length === 0) return; const id = this.nextBattalionId++; const unitIds = new Set(selected.map((u) => u.id)); selected.forEach((u) => u.battalionId = id); this.battalions = this.battalions.filter((b) => [...b.unitIds].every((unitId) => !unitIds.has(unitId))); this.battalions.push({ id, name: `Отряд ${id}`, unitIds, formation: this.formation, angle: 0 }); }
  private ungroupSelectedBattalions(): void { const selectedBattalionIds = new Set(this.getSelectedBattalions().map((b) => b.id)); if (selectedBattalionIds.size === 0) return; this.units.forEach((u) => { if (u.battalionId && selectedBattalionIds.has(u.battalionId)) u.battalionId = null; }); this.battalions = this.battalions.filter((b) => !selectedBattalionIds.has(b.id)); }
  private reformSelectedInPlace(): void { const selected = this.units.filter((u) => this.selectedIds.has(u.id)); if (selected.length === 0) return; const center = selected.reduce((acc, u) => acc.add(u.world.clone()), new Phaser.Math.Vector2(0, 0)).scale(1 / selected.length); this.issueMoveCommand(center.x, center.y, this.getSelectedBattalions()[0]?.angle ?? 0); }
  private expandSelectionToBattalions(): void { const touchedBattalionIds = new Set(this.units.filter((u) => this.selectedIds.has(u.id) && u.battalionId !== null).map((u) => u.battalionId as number)); this.units.forEach((unit) => { if (unit.battalionId !== null && touchedBattalionIds.has(unit.battalionId)) { unit.selected = true; this.selectedIds.add(unit.id); } }); }
  private getSelectedBattalions(): Battalion[] { return this.battalions.filter((b) => [...b.unitIds].some((id) => this.selectedIds.has(id))); }
  private updateUnits(units: Unit[], delta: number): void { for (const unit of units) { if (!unit.target) { this.syncUnitSprite(unit); continue; } const dist = Phaser.Math.Distance.Between(unit.world.x, unit.world.y, unit.target.x, unit.target.y); if (dist < 0.05) { unit.target = null; this.syncUnitSprite(unit); continue; } const step = unit.speed * delta / 1000; const angle = Phaser.Math.Angle.Between(unit.world.x, unit.world.y, unit.target.x, unit.target.y); unit.world.x += Math.cos(angle) * Math.min(step, dist); unit.world.y += Math.sin(angle) * Math.min(step, dist); this.syncUnitSprite(unit); } }
  private syncUnitSprite(unit: Unit): void { const p = worldToIso(unit.world.x, unit.world.y); unit.sprite.setPosition(p.x, p.y); unit.label.setPosition(p.x, p.y - 18); const d = isoDepth(unit.world.x, unit.world.y); unit.sprite.setDepth(d); unit.label.setDepth(d + 1); }
  private updateCombat(time: number): void { for (const unit of this.units) { if (unit.range <= 0) continue; const target = this.findNearest(unit, this.enemies, unit.range); if (target && unit.ammo > 0 && time - unit.lastShotAt > unit.reloadMs) this.fire(unit, target, time); } for (const unit of this.enemies) { if (unit.range <= 0) continue; const target = this.findNearest(unit, this.units, unit.range); if (target && unit.ammo > 0 && time - unit.lastShotAt > unit.reloadMs) this.fire(unit, target, time); } this.units = this.units.filter((u) => u.hp > 0 && u.morale > 0); this.enemies = this.enemies.filter((u) => u.hp > 0 && u.morale > 0); this.resources.population = this.units.length; this.battalions.forEach((b) => b.unitIds = new Set([...b.unitIds].filter((id) => this.units.some((u) => u.id === id)))); this.battalions = this.battalions.filter((b) => b.unitIds.size > 0); }
  private findNearest(unit: Unit, targets: Unit[], range: number): Unit | null { let best: Unit | null = null; let bestDist = range; for (const target of targets) { const dist = Phaser.Math.Distance.Between(unit.world.x, unit.world.y, target.world.x, target.world.y); if (dist < bestDist) { best = target; bestDist = dist; } } return best; }
  private fire(unit: Unit, target: Unit, time: number): void { unit.lastShotAt = time; unit.ammo -= 1; target.hp -= unit.damage; target.morale -= unit.moraleDamage; const color = unit.kind === 'artillery' ? 0xfb923c : unit.kind === 'specialist' ? 0xc084fc : 0xfef08a; const a = worldToIso(unit.world.x, unit.world.y); const b = worldToIso(target.world.x, target.world.y); const shot = this.add.line(0, 0, a.x, a.y, b.x, b.y, color, 0.8).setOrigin(0).setDepth(4500); this.addSmoke(b.x, b.y); if (unit.kind === 'artillery') this.applySplashDamage(target, 1.1, unit.damage * 0.45, unit.moraleDamage * 0.5); this.time.delayedCall(unit.kind === 'artillery' ? 160 : 90, () => shot.destroy()); if (target.hp <= 0 || target.morale <= 0) this.destroyUnit(target); }
  private addSmoke(x: number, y: number): void { const smoke = this.add.circle(x, y - 10, 10, 0xd6d3d1, 0.45).setDepth(4600); this.tweens.add({ targets: smoke, alpha: 0, radius: 24, y: y - 26, duration: 500, onComplete: () => smoke.destroy() }); }
  private applySplashDamage(center: Unit, radius: number, damage: number, moraleDamage: number): void { const pool = this.units.includes(center) ? this.units : this.enemies; pool.forEach((target) => { if (target.id === center.id) return; const dist = Phaser.Math.Distance.Between(center.world.x, center.world.y, target.world.x, target.world.y); if (dist <= radius) { target.hp -= damage; target.morale -= moraleDamage; if (target.hp <= 0 || target.morale <= 0) this.destroyUnit(target); } }); }
  private destroyUnit(unit: Unit): void { unit.sprite.destroy(); unit.label.destroy(); }
  private renderUnitState(): void { for (const unit of [...this.units, ...this.enemies]) { unit.sprite.setStrokeStyle(unit.selected ? 3 : 1, unit.selected ? 0xfacc15 : 0x111827); unit.sprite.setAlpha(Math.max(0.25, unit.morale / UNIT_SPECS[unit.kind].morale)); unit.label.setVisible(unit.selected || unit.kind === 'artillery' || unit.kind === 'cavalry'); } }
  private renderBuildingState(): void { for (const building of this.buildings) building.sprite.setStrokeStyle(building.selected ? 4 : 2, building.selected ? 0xfacc15 : 0x111827); }
  private renderBattalions(): void { this.battalionGraphics.clear(); this.getSelectedBattalions().forEach((b) => { const members = this.units.filter((u) => b.unitIds.has(u.id)); if (members.length === 0) return; const minX = Math.min(...members.map((u) => u.sprite.x)); const maxX = Math.max(...members.map((u) => u.sprite.x)); const minY = Math.min(...members.map((u) => u.sprite.y)); const maxY = Math.max(...members.map((u) => u.sprite.y)); this.battalionGraphics.lineStyle(2, 0x38bdf8, 0.75).strokeRect(minX - 16, minY - 16, maxX - minX + 32, maxY - minY + 32); }); }
  private updateCamera(delta: number): void { const keys = this.input.keyboard?.addKeys('W,A,S,D') as Record<string, Phaser.Input.Keyboard.Key> | undefined; if (!keys) return; const cam = this.cameras.main; const speed = 420 * delta / 1000; if (keys.A.isDown) cam.scrollX -= speed; if (keys.D.isDown) cam.scrollX += speed; if (keys.W.isDown) cam.scrollY -= speed; if (keys.S.isDown) cam.scrollY += speed; }
  private clearSelection(): void { this.selectedBuildingId = null; this.selectedIds.clear(); this.units.forEach((unit) => unit.selected = false); this.buildings.forEach((building) => building.selected = false); }
  private updateHud(): void { const width = this.scale.width; const height = this.scale.height; const selected = this.units.filter((u) => this.selectedIds.has(u.id)); const battalions = this.getSelectedBattalions(); const selectedBuilding = this.buildings.find((b) => b.id === this.selectedBuildingId) ?? null; this.topBar.setText(`🍞 ${this.resources.food}   🪵 ${this.resources.wood}   ⛏ ${this.resources.iron}   🪙 ${this.resources.gold}   👥 ${this.resources.population}/${this.resources.populationCap}   Formation: ${this.formation}   Buildings: ${this.buildings.length}`); this.bottomPanel.clear(); this.bottomPanel.fillStyle(0x1b120c, 0.92).fillRect(0, height - 154, width, 154); this.bottomPanel.lineStyle(3, 0x8b6f3e, 1).lineBetween(0, height - 154, width, height - 154); const selectedCounts = UNIT_KINDS.reduce<Record<UnitKind, number>>((acc, kind) => { acc[kind] = selected.filter((u) => u.kind === kind).length; return acc; }, { worker: 0, soldier: 0, specialist: 0, cavalry: 0, artillery: 0 }); const units = UNIT_KINDS.map((kind) => ({ kind, label: UNIT_SPECS[kind].label, short: UNIT_SPECS[kind].short, color: UNIT_SPECS[kind].color, count: selectedCounts[kind], total: this.units.filter((u) => u.kind === kind).length })); this.portraitPanel.render(12, height - 146, { units, selectedBuilding, selectedUnitCount: selected.length, selectedBattalionCount: battalions.length, placementLabel: this.placementKind ? BUILDING_SPECS[this.placementKind].label : null }); this.drawMinimap(width - 218, height - 142, 200, 124); }
  private drawMinimap(x: number, y: number, w: number, h: number): void { const cam = this.cameras.main; this.minimap.clear(); this.minimap.fillStyle(0x050814, 0.92).fillRect(x, y, w, h); this.minimap.lineStyle(2, 0xd6b86a, 1).strokeRect(x, y, w, h); this.minimap.fillStyle(0x376b42, 1).fillRect(x + 4, y + 4, w - 8, h - 8); const sx = w / WORLD_WIDTH; const sy = h / WORLD_HEIGHT; this.buildings.forEach((b) => this.minimap.fillStyle(BUILDING_SPECS[b.kind].color, 1).fillRect(x + b.world.x * sx, y + b.world.y * sy, 3, 3)); this.units.forEach((u) => this.minimap.fillStyle(UNIT_SPECS[u.kind].color, 1).fillRect(x + u.world.x * sx, y + u.world.y * sy, 2, 2)); this.enemies.forEach((u) => this.minimap.fillStyle(0xdc2626, 1).fillRect(x + u.world.x * sx, y + u.world.y * sy, 2, 2)); const topLeft = isoToWorld(cam.scrollX, cam.scrollY); const bottomRight = isoToWorld(cam.scrollX + cam.width, cam.scrollY + cam.height); this.minimap.lineStyle(1, 0xffffff, 0.8).strokeRect(x + Math.min(topLeft.x, bottomRight.x) * sx, y + Math.min(topLeft.y, bottomRight.y) * sy, Math.abs(bottomRight.x - topLeft.x) * sx, Math.abs(bottomRight.y - topLeft.y) * sy); }
}
